experiments:
  exp_ournet1_baseline:
    model:
      name: ournet1
      num_classes: 100
      dropout: 0.3
    
    train:
      lr: 0.0001
      epochs: 100
      patience: 10
      optimizer: "adam"              
      loss: "crossentropy" 
    
    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp1

  exp_ournet2_baseline:
    model:
      name: ournet2
      num_classes: 100
      dropout: 0.3

    train:
      lr: 0.0001
      epochs: 100
      patience: 10
      optimizer: "adam"
      loss: "crossentropy"

    scheduler:
      type: steplr
      step_size: 10
      gama: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    
    experiment: exp2

  exp_alexnet_baseline:
    model:
      name: alexnet_pre
      num_classes: 100
      dropout: 0.0        
    
    train:
      lr: 0.0001
      epochs: 100
      patience: 10
      optimizer: adam
      loss: crossentropy
    
    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp3
      
  exp_resnet18_pretrain_baseline:
    model:
      name: resnet18_pre
      num_classes: 100
      dropout: 0.0        
    
    train:
      lr: 0.0001
      epochs: 20
      patience: 5
      optimizer: adam
      loss: crossentropy
    
    scheduler:
      type: steplr
      step_size: 5
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp4

  exp_resnet18_baseline:
    model:
      name: resnet18
      num_classes: 100
      dropout: 0.0        
    
    train:
      lr: 0.0001
      epochs: 100
      patience: 10
      optimizer: adam
      loss: crossentropy
    
    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp5
