experiments:
  exp_ournet_baseline:
    model:
      name: ournet
      num_classes: 100
      dropout: 0.3
    
    train:
      lr: 0.0001
      epochs: 50
      patience: 10
      optimizer: "adam"              
      loss: "crossentropy" 
    
    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp1

  ournetv2_on2_experiment:
    model:
      name: "On2"
      num_classes: 100

    train:
      lr: 0.0005
      epochs: 70
      patience: 10
      optimizer: adam
      loss: crossentropy

    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 64
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp2

  exp_alexnet_finetune:
    model:
      name: alexnet_pre
      num_classes: 100
      dropout: 0.0        
    
    train:
      lr: 0.0001
      epochs: 100
      patience: 10
      optimizer: adam
      loss: crossentropy
    
    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp3

  exp_alexnet_scratch:
    model:
      name: alexnet_scratch
      num_classes: 100
      dropout: 0.0        
    
    train:
      lr: 0.0001
      epochs: 100
      patience: 10
      optimizer: adam
      loss: crossentropy
    
    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp4
      
  exp_resnet18_baseline:
    model:
      name: exp_resnet18_baseline
      num_classes: 100
      dropout: 0.0        
    
    train:
      lr: 0.0001
      epochs: 100
      patience: 5
      optimizer: adam
      loss: crossentropy
    
    scheduler:
      type: steplr
      step_size: 5
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp5

  exp_restnet_scratch:
    model:
      name: resnet18_scratch
      num_classes: 100
      dropout: 0.0        
    
    train:
      lr: 0.0001
      epochs: 100
      patience: 5
      optimizer: adam
      loss: crossentropy
    
    scheduler:
      type: steplr
      step_size: 5
      gamma: 0.5

    data:
      batch_size: 32
      image_size: 224
      split_pct: 0.2
      seed: 42
    experiment:
      name: exp6

  exp_restnet_scratch_no_aug:
    model:
      name: resnet18_scratch
      num_classes: 100
      dropout: 0.0

    train:
      lr: 0.0005
      epochs: 50
      patience: 10
      optimizer: adam
      loss: crossentropy

    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 64
      image_size: 224
      split_pct: 0.2
      seed: 42

    experiment:
      name: exp7
      
  exp_resnet18_dataset_norm:
    model:
      name: resnet18
      num_classes: 100
      dropout: 0.0

    train:
      lr: 0.0005
      epochs: 50
      patience: 10
      optimizer: adam
      loss: crossentropy

    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 64
      image_size: 224
      split_pct: 0.2
      seed: 42
      augmentations:
        horizontal_flip: true
        random_crop: true
        random_rotation: 15
        color_jitter: true
    experiment:
      name: exp8

  exp_resnet_grayscale:
    model:
      name: resnet18
      num_classes: 100
      dropout: 0.0

    train:
      lr: 0.0005
      epochs: 50
      patience: 10
      optimizer: adam
      loss: crossentropy

    scheduler:
      type: steplr
      step_size: 10
      gamma: 0.5

    data:
      batch_size: 64
      image_size: 224
      split_pct: 0.2
      seed: 42

    experiment:
      name: exp9